services:
  # Backend API Service
  - type: web
    name: game-lobby-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # You'll set this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random value
      - key: CORS_ORIGIN
        sync: false # You'll set this manually after frontend is deployed
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: game-lobby-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false # You'll set this manually after backend is deployed
      - key: VITE_SOCKET_URL
        sync: false # You'll set this manually after backend is deployed
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
